/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/todolists/{listId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemDTO"][];
                        "application/json": components["schemas"]["TodoItemDTO"][];
                        "text/json": components["schemas"]["TodoItemDTO"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateItemDTO"];
                    "text/json": components["schemas"]["CreateItemDTO"];
                    "application/*+json": components["schemas"]["CreateItemDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemDTO"];
                        "application/json": components["schemas"]["TodoItemDTO"];
                        "text/json": components["schemas"]["TodoItemDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todolists/{listId}/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoItemDTO"];
                        "application/json": components["schemas"]["TodoItemDTO"];
                        "text/json": components["schemas"]["TodoItemDTO"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateItemDTO"];
                    "text/json": components["schemas"]["UpdateItemDTO"];
                    "application/*+json": components["schemas"]["UpdateItemDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todolists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoList"][];
                        "application/json": components["schemas"]["TodoList"][];
                        "text/json": components["schemas"]["TodoList"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateListDTO"];
                    "text/json": components["schemas"]["CreateListDTO"];
                    "application/*+json": components["schemas"]["CreateListDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoList"];
                        "application/json": components["schemas"]["TodoList"];
                        "text/json": components["schemas"]["TodoList"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todolists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TodoList"];
                        "application/json": components["schemas"]["TodoList"];
                        "text/json": components["schemas"]["TodoList"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateListDTO"];
                    "text/json": components["schemas"]["UpdateListDTO"];
                    "application/*+json": components["schemas"]["UpdateListDTO"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todolists/{listId}/complete-all-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    listId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompleteAllItemsResponseDTO"];
                        "application/json": components["schemas"]["CompleteAllItemsResponseDTO"];
                        "text/json": components["schemas"]["CompleteAllItemsResponseDTO"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CompleteAllItemsResponseDTO: {
            operationId?: string | null;
            /** Format: int32 */
            total?: number;
        };
        CreateItemDTO: {
            description: string | null;
        };
        CreateListDTO: {
            name: string | null;
        };
        TodoItem: {
            /** Format: int64 */
            id?: number;
            description: string | null;
            isCompleted?: boolean;
            /** Format: int64 */
            todoListId?: number;
            todoList?: components["schemas"]["TodoList"];
        };
        TodoItemDTO: {
            /** Format: int64 */
            id?: number;
            description: string | null;
            isCompleted?: boolean;
        };
        TodoList: {
            /** Format: int64 */
            id?: number;
            name: string | null;
            todoItems?: components["schemas"]["TodoItem"][] | null;
        };
        UpdateItemDTO: {
            description: string | null;
            isCompleted?: boolean;
        };
        UpdateListDTO: {
            name: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
